# Generated by Django 5.2.11 on 2026-02-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_delete_add_remove_order_product_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(default='photo not null', upload_to='categories/'),
            preserve_default=False,
        ),
    ]
