# Generated by Django 5.2.11 on 2026-03-02 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.CharField(choices=[('review', "ko'rib chiqish"), ('complete', 'Yakunlandi'), ('canceled', 'rad etildi')], default='review')),
                ('check_photo', models.ImageField(upload_to='pays/')),
                ('pay_datetime', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('coin', 'tanga'), ('money', 'pul')], default='money')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
