# Generated by Codex on 2026-03-08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0005_wishlist"),
        ("apps", "0006_payment"),
    ]

    operations = []

