# Generated by Codex on 2026-03-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0007_merge_wishlist_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, blank=True, db_index=True, null=True),
        ),
    ]

