# Generated by Codex on 2026-03-08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0008_payment_created_at_payment_updated_at_and_more"),
        ("apps", "0008_product_created_at"),
    ]

    operations = []

