# Generated by Codex on 2026-03-08

from django.db import migrations


def fill_created_at(apps, schema_editor):
    Product = apps.get_model("apps", "Product")
    from django.utils import timezone

    Product.objects.filter(created_at__isnull=True).update(created_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0009_merge_payment_product_created_at"),
    ]

    operations = [
        migrations.RunPython(fill_created_at, migrations.RunPython.noop),
    ]

