# Generated by Django 5.2.11 on 2026-03-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0015_promo_codes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
    ]
