# Generated by Django 5.2.11 on 2026-03-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0016_remove_user_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PromoCodeRedemption",
        ),
        migrations.DeleteModel(
            name="PromoCode",
        ),
    ]
