# Generated by Codex on 2026-03-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0017_delete_promo_models"),
        ("apps", "0004_product_indexes"),
    ]

    operations = []

